### PR TITLE
[DEVOPS-2284] bump actions-core to v1.10.0

### PR DESCRIPTION
**Pull request by darzu-gap**
GitHub Actions: Deprecating save-state and set-output commands
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### CODE REVIEW

**Review by johnheusinger — APPROVED** [review]
LGTM

**Comment by johnheusinger** [comment]
On second thought, I wonder if a better approach would be to get our fork synced with the origin and point to a newer version of the action 🤔

**Review by EnterPin — COMMENTED** [review]
i concur.

**Comment by darzu-gap** [comment]
I reviewed the code from Julian and it all seem good most of the commits were made with a bot just to update dependencies. so now we are sync with the fork

**Pull request closed without merging**
